---
title: "Trait variation across spatiotemporal scales"
author: "Pat Dumandan"
date: "12/14/2020"
output: html_document
---
   Characterizing natural variation and identifying its drivers have been central goals of many biological studies that aim to obtain a mechanistic understanding of how ecological systems respond to increasing global environmental change (Orlowsky and Seneviratne, 2011; Pereira et al., 2010). For example, shifts in population density and community composition across an environmental gradient provide evidence for the profound impacts of climate variability on biodiversity patterns (Spaak et al., 2017). Moreover, variations in trait distributions are assessed to test theories explaining community dynamics (Lichstein et al., 2007). As such, identifying and quantifying different types of variation observed in nature will advance our understanding of ecosystem dynamics (Albert et al., 2011).   

   A facet of natural variation that has recently gained increased attention is on niche differentiation among (interspecific trait variation, BTV) and within (intraspecific trait variation, ITV) species (Violle et al., 2012, Jung et al. 2010). Contrasting theories have been offered to explain when and how each type of trait variation is important in driving coexistence patterns (Albert et al., 2011; Lichstein et al. 2007). These contrasting views may be because traits are not homogeneous in space and time (Violle et al., 2014), and the relative importance of the processes that underlie the variation in the magnitude of intra- and interspecific trait variation can vary across ecological scales (Albert et al., 2011; Messier et al., 2010). However, despite the recognition of the role of both types of trait variation and their scale-dependent effects, few studies have simultaneously assessed how both vary across space and time.  
   
   The effects of scale in interpreting biodiversity patterns have also been increasingly recognized. In fact, these patterns are consequences of complex spatiotemporal processes that vary across ecological scales (Storch et al., 2007). As such, failing to account for scale effects can lead to incorrect inferences on diversity patterns in spatially and temporally variable environments (Falke et al., 2020; White, 2007). Thus, identifying at which scales we can expect higher intra- and interspecific trait variation will be useful in testing assumptions of existing theories on trait distribution.  
   
   The distribution of traits that reflect species adaptation, performance, and function in a given environmental context (functional traits) provides insights on ecosystem dynamics (McGill et al., 2006).  A key functional trait in many organisms is their body size, owing to its role in driving ecological interactions (Brown et al., 1993; Blanchard et al., 2011). As such, availability of data on this key trait is generally abundant for multiple taxa. However, oftentimes, measurement data are reduced to mean values, which reflects niche position but not niche breadth (Violle and Jang, 2009). Assessing shifts in patterns of niche breadth and its drivers is important because it offers a nuanced understanding of how functional diversity is maintained (He et al., 2018).  
   
   Here, we describe the scaling patterns of both intra- and interspecific variation in a key functional trait. Specifically, we assess how both types of variation in body mass of rodents are distributed across spatiotemporal scales and identify the role of climatic conditions in driving these variation patterns. We describe the magnitude of ITV and BTV by calculating the coefficient of variation (cv) in the body mass of rodents across three nested spatial scales (plot, site, region) for each time scale (month, season, year, decade). Then, we build hierarchical models to assess the association between each type of variation with proximate climate variables. By exploring the patterns in the variance components of a key functional trait, we gain more insights on the ecological strategies that underlie community assembly, which may be useful in advancing the predictive power of trait-based ecology.   
   
REFERENCES:

Albert, C. H., Grassein, F., Schurr, F. M., Vieilledent, G., & Violle, C. (2011). When and how should intraspecific variability be considered in trait-based plant ecology?. Perspectives in Plant Ecology, Evolution and Systematics, 13(3), 217-225.  
Blanchard, J. L., Law, R., Castle, M. D., & Jennings, S. (2011). Coupled energy pathways and the resilience of size-structured food webs. Theoretical Ecology, 4(3), 289–300. https://doi.org/10.1007/s1208 0-010-0078-9  
Brown, J. H., Marquet, P. A., & Taper, M. L. (1993). Evolution of body size: Consequences of an energetic definition of fitness. The American Naturalist, 142(4), 573–584. https://doi.org/10.1086/285558  
Falke, L. P., Henderson, J. S., Novak, M., & Preston, D. L. (2020). Temporal shifts in intraspecific and interspecific diet variation among 3 stream predators. Freshwater Science, 39(1), 115-125.  
He, D., Chen, Y., Zhao, K., Cornelissen, J. H. C., & Chu, C. (2018). Intra-and interspecific trait variations reveal functional relationships between specific leaf area and soil niche within a subtropical forest. Annals of botany, 121(6), 1173-1182.  
Jung, V., Violle, C., Mondy, C., Hoffmann, L., & Muller, S. (2010). Intraspecific variability and trait‐based community assembly. Journal of ecology, 98(5), 1134-1140.    
Lichstein, J. W., J. Dushoff, S. A. Levin, and S. W. Pacala. 2007. Intraspecific variation and species coexistence. The American Naturalist 170:807–818  
Messier, J., McGill, B. J., & Lechowicz, M. J. (2010). How do traits vary across ecological scales? A case for trait‐based ecology. Ecology letters, 13(7), 838-848.  
Orlowsky, B., & Seneviratne, S. I. (2012). Global changes in extreme events: regional and seasonal dimension. Climatic Change, 110(3-4), 669-696.   
Pereira, H. M., Leadley, P. W., Proença, V., Alkemade, R., Scharlemann, J. P., Fernandez-Manjarrés, J. F., ... & Chini, L. (2010). Scenarios for global biodiversity in the 21st century. Science, 330(6010), 1496-1501.  
Spaak, J. W., Baert, J. M., Baird, D. J., Eisenhauer, N., Maltby, L., Pomati, F., Radchuk, V., Rohr, J. R., Van den Brink, P. J., & De Laender, F. (2017). Shifts of community composition and population density substantially affect ecosystem function despite invariant richness. Ecology Letters, 20(10), 1315–1324. https://doi.org/10.1111/ele.12828  
Storch, D., Marquet, P. A., & Brown, J. H. (2007). Scaling biodiversity. Cambridge University Press. Cambridge, UK.  
Violle C, Enquist BJ, McGill BJ, et al. 2012. The return of the variance: intraspecific variability in community ecology. Trends in Ecology & Evolution 27: 244–252  
Violle C, Jiang L. 2009. Towards a trait-based quantification of species niche. Journal of Plant Ecology 2: 87–93.   
White, E. P. (2007). Spatiotemporal scaling of species richness: patterns, processes, and implications. In Scaling biodiversity (D. Storch, P. A. Marquet, J. H. Brown eds). Cambridge University Press. Cambridge, UK.  